name: ‚úÖ CI
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        perl: [ '5.40', '5.38', '5.36', '5.34', '5.32', '5.30', '5.28', '5.26', '5.24', '5.22', '5.20', '5.18', '5.16', '5.14', '5.12', '5.10', '5.8' ]
    name: üê™ Perl ${{ matrix.perl }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
        env:
          AUTHOR_TESTING: 1
          RELEASE_TESTING: 1
      - name: Build and Test
        # Have to build on Windows to get scripts\psql.bat.
        run: |
          perl -V
          cpanm --notest --installdeps . # https://github.com/Perl-Toolchain-Gang/extutils-pl2bat/issues/7
          perl Build.PL
          perl Build code
          prove -lv t
